Repository SINTEF/PySilCam, pull requests merged in 2020-12, with the labels that each got.

#74 File handling modifications in tests
  pysilcam/tests/test_process.py
  pysilcam/tests/test_standards.py
  pysilcam/tests/test_z_speed.py
Labels: bug

#47 Update README.md
  README.md
Labels: documentation

#70 55 h5stats
  pysilcam/__main__.py
  pysilcam/oilgas.py
  pysilcam/plotting.py
  pysilcam/postprocess.py
  pysilcam/silcamgui/guicalcs.py
  pysilcam/silcamgui/interactive_summary.py
  pysilcam/silcamgui/silcamgui.py
  pysilcam/silcreport.py
  pysilcam/tests/test_process.py
  pysilcam/tests/test_standards.py
  tfl_tools/investigate_particles.py
  tfl_tools/silcam_classifier_database_builder.py
  tfl_tools/silcam_self_learn.py
Labels: enhancement

#87 add stats csv converter to postprocess
  pysilcam/postprocess.py
  pysilcam/tests/test_stats_convert.py
Labels: enhancement

#88 81 interactive summary bug
  environment.yml
  pysilcam/silcamgui/interactive_summary.py
Labels: bug

#71 Tracking
  environment.yml
  pysilcam/config.py
  pysilcam/config_example.ini
  pysilcam/fakepymba.py
  pysilcam/silcamgui/guicalcs.py
  pysilcam/tests/test_tracking.py
  pysilcam/tracking/silcamtracker.py
  pysilcam/tracking/track.py
  setup.py
Labels: enhancement
