Repository SINTEF/PySilCam, pull requests merged in 2020-04, with the labels that each got.

#2 Cleaned README.md according to markdown linting rules
  README.md
Labels: documentation

#33 Viewer improvements
  .gitignore
  pysilcam/silcamgui/guicalcs.py
  pysilcam/silcamgui/liveviewer.py
Labels: enhancement

#20 fix failing tests due to disc space
  .github/workflows/docker-build-and-test.yml
  pysilcam/tests/test_process.py
  pysilcam/tests/test_standards.py
Labels: bug
