Repository SINTEF/PySilCam, pull requests merged in 2021-03, with the labels that each got.

#104 103 change andaconda to conda-forge
  environment.yml
  pysilcam/silcamgui/interactive_summary.py
Labels: bug, enhancement, size: 1

#109 ReadTheDocs docs
  .readthedocs.yaml
  README.md
  docs/source/conf.py
  docs/source/index.rst
  pysilcam/__init__.py
  setup.py
Labels: documentation, enhancement

#118 90 tidy versioning
  docs/source/conf.py
  pysilcam/config.py
  pysilcam/config_example.ini
  pysilcam/silcamgui/__init__.py
  pysilcam/tests/test_config.py
  shell_tools/hardware_testing/config_hardware_test.ini
Labels: enhancement

#120 fix display of GOR in realtime mode
  pysilcam/__init__.py
  pysilcam/__main__.py
  pysilcam/oilgas.py
  pysilcam/postprocess.py
  pysilcam/silcamgui/guicalcs.py
Labels: bug

#123 115 bugfix process hanging
  pysilcam/__init__.py
  pysilcam/oilgas.py
  pysilcam/postprocess.py
  pysilcam/process.py
  pysilcam/tests/test_z_classify.py
Labels: bug

#121 119 remove gca type plotting calls
  pysilcam/__init__.py
  pysilcam/silcamgui/guicalcs.py
Labels: bug

#124 Version check
  .github/workflows/version_check.yml
  pysilcam/__init__.py
Labels: documentation, enhancement, testing

#128 127 bugfix gor key error
  pysilcam/__init__.py
  pysilcam/__main__.py
Labels: PyQt, bug

#129 122 append to empty stats
  pysilcam/__init__.py
  pysilcam/__main__.py
  pysilcam/process.py
Labels: bug
